# PDF report generation utilities
# app/utils/pdf_generator.py

import os
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import Table, TableStyle


def generate_medical_report(user_id, predicted_class, confidence, risk_level, recommendation):

    # Ensure reports directory exists
    reports_dir = "reports"
    os.makedirs(reports_dir, exist_ok=True)

    # File name with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_name = f"medical_report_{user_id}_{timestamp}.pdf"
    file_path = os.path.join(reports_dir, file_name)

    # Create PDF document
    doc = SimpleDocTemplate(file_path)
    elements = []

    styles = getSampleStyleSheet()

    # Title
    title_style = styles["Heading1"]
    elements.append(Paragraph("AI Multi Disease Diagnosis Report", title_style))
    elements.append(Spacer(1, 0.3 * inch))

    # Date
    date_text = f"Generated On: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    elements.append(Paragraph(date_text, styles["Normal"]))
    elements.append(Spacer(1, 0.3 * inch))

    # Table Data
    data = [
        ["Patient ID", str(user_id)],
        ["Predicted Disease", predicted_class],
        ["Confidence", f"{confidence} %"],
        ["Risk Level", risk_level],
        ["Recommendation", recommendation]
    ]

    table = Table(data, colWidths=[2.5 * inch, 3.5 * inch])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 0.5 * inch))

    # Disclaimer
    disclaimer_style = ParagraphStyle(
        name="Disclaimer",
        fontSize=9,
        textColor=colors.red
    )

    disclaimer_text = (
        "Disclaimer: This report is generated by an AI system. "
        "It is intended for preliminary screening only and does not replace professional medical diagnosis."
    )

    elements.append(Paragraph(disclaimer_text, disclaimer_style))

    # Build PDF
    doc.build(elements)

    return file_path